name: flutter_mvvm_template
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  http: ^1.1.0
  dio: ^5.3.2
  connectivity_plus: ^6.1.4
  package_info_plus: ^8.3.0
  curl_logger_dio_interceptor: ^1.0.0
  provider: ^6.0.5
  path_provider: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.6
  mockito: ^5.3.2
  mocktail: ^1.0.4
  http_mock_adapter: ^0.6.0
  test_cov_console: ^0.2.2
  flutter_driver:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/config/

  # To add custom fonts to your application, add a fonts section here,
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700